### ISSUE TITLE
使用 now dev 运行时报错

### ISSUE THREAD

**Issue by shuiRong** [xuthus5/zeit-serverless#1]
```
now --version
21.0.1

go version go1.16.2 darwin/amd64
```

操作步骤：
1. clone 仓库
2. `now dev --debug --listen 8080`
3. 一路 Y/N 之后，访问`http://localhost:8080/api/version`，保存

先是报错了：
```
go: cannot find main module, but found .git/config in /Users/shuirong/Code/Golang/zeit-serverless
	to create a module there, run:
	cd ../../../.. && go mod init
```
通过在根目录，`go mod init test`解决掉了。
然后遇到第二个错：
```
api/entrypoint.go:10:2: no required module provides package github.com/jinzhu/gorm; to add it:
	go get github.com/jinzhu/gorm
api/entrypoint.go:11:2: no required module provides package github.com/jinzhu/gorm/dialects/sqlite; to add it:
	go get github.com/jinzhu/gorm/dialects/sqlite
> [debug] [2021-03-27T14:33:57.420Z] Error starting "@vercel/go" dev server: Error: Failed to start dev server for "api/version_go.go" (code=1, signal=null)
```
这个解决了一会儿搞不定，请问有解决方法吗?

**Comment by xuthus5** [comment]
运行命令 go mod download或者 go mod tidy以解决依赖问题

**Comment by shuiRong** [comment]
已经（在根目录，api目录）尝试过了，不行。

**Comment by shuiRong** [comment]
诶，解决不掉这个问题。Vercel issue区没有几个Go相关的问题，Discussion区倒是有几个，但都解决不了问题。1月份有一个一样的问题还在那挂着呢。

放弃了，转用Heroku来部署Golang程序了，倒是顺利的很，[测试接口](https://warm-reef-76661.herokuapp.com/ping)。

**Comment by shuiRong** [comment]
再补充下，似乎这是在 Big Sur 才出现的问题

https://github.com/vercel/vercel/discussions/5725#discussioncomment-559218
